let me ={
    junish: {
        name:'JUNISH ARORA',
        headline:'DEVELOPER',
        bio:'I LOVE TO WRITE CODE , IT IS SOMETHING THAT CAN RAISE YOU AT A DIFFERENT LEVEL. I STARTED LEARNING THIS IN 2022 BUT NOW I AM SURE I AM BEING INTO IT FOR WHOLE OF MY LIFE',
    },

    logan: {
        name:'LOGAN HUFFMAN',
        headline:'DESIGNER',
        bio:'I LOVE TO DESIGN THINGS IN PHOTOSHOP, IT IS A LOT OF FUN. MY FAVOURITE TYPE OF THINGS TO DESIGN IN PHHOTOSOHP ARE USER INTERFACES & LOGOS/ICONS.',
    },
}